[observation_property]
OBSERVER = "amigos"
OBJECT = "M17SW"
MOLECULE_1 = "J10_12CO"

[coordinate]
LamdaOn = "-84.9232deg"
BetaOn = "-16.2003deg"
#RELATIVE = false
LamdaOff = "-83.5587deg"
BetaOff = "-16.6110deg"
#deltaLambda = {}
#deltaBeta = {}
OTADEL = true
COORD_SYS = "J2000"

[pointing_property]
METHOD = 9
GridAz = "30arcsec"
GridEl = "30arcsec"
integ_on = "10s"
OffsetAz = "0arcsec"
OffsetEl = "0arcsec"

[calibration]
integ_off = "10s"
integ_hot = "10s"
off_interval = 1
load_interval = "5min"
