[observation_property]
OBSERVER = "amigos"
OBJECT = "IRC10216"
MOLECULE_1 = "12CO10"

[coordinate]
LambdaOn = "146.98871deg"
BetaOn = "13.278574deg"
RELATIVE = false
LambdaOff = "147.23930deg"
BetaOff = "13.279295deg"
deltaLambda = {}
deltaBeta = {}
COORD_SYS = "J2000"

#position_angle = "0deg"
#OTADEL = true

[pointing_property]
METHOD = 9
GridX = "30arcsec"
GridY = "30arcsec"
integ_on = "10s"

[calibration]
integ_off = "10s"
integ_hot = "10s"
off_interval = 1
load_interval = "5min"
